omni_manipulator:
  #Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000

  gazebo_ros_control:
    pid_gains:
      joint_1: {p: 150.0, i: 10.0, d: 1.0}
      joint_2: {p: 150.0, i: 10.0, d: 1.0}
      joint_3: {p: 150.0, i: 10.0, d: 1.0}
      joint_4: {p: 150.0, i: 10.0, d: 1.0}
      joint_5: {p: 150.0, i: 10.0, d: 1.0}
      joint_6: {p: 150.0, i: 10.0, d: 1.0}
  #     right_front_mecanum_joint: {p: 100.0, i: 1.0, d: 10.0}
  #     left_front_mecanum_joint: {p: 100.0, i: 1.0, d: 10.0}
  #     left_back_mecanum_joint: {p: 100.0, i: 1.0, d: 10.0}
  #     right_back_mecanum_joint: {p: 100.0, i: 1.0, d: 10.0}
  #     finger_R_joint: {p: 20.0, i: 0.1, d: 0.0}
  #     finger_L_joint: {p: 20.0, i: 0.1, d: 0.0}
  
  # Position Controllers ---------------------------------------
  joint_1_pos:
    type: position_controllers/JointPositionController
    joint: joint_1
    pid: {p: 100.0, i: 1.0, d: 10.0}
    
  joint_2_pos:
    type: position_controllers/JointPositionController
    joint: joint_2
    pid: {p: 100.0, i: 1.0, d: 10.0}
    
  joint_3_pos:
    type: position_controllers/JointPositionController
    joint: joint_3
    pid: {p: 100.0, i: 1.0, d: 10.0}
    
  joint_4_pos:
    type: position_controllers/JointPositionController
    joint: joint_4
    pid: {p: 100.0, i: 1.0, d: 10.0}
    
  joint_5_pos:
    type: position_controllers/JointPositionController
    joint: joint_5
    pid: {p: 100.0, i: 1.0, d: 10.0}
    
  joint_6_pos:
    type: position_controllers/JointPositionController
    joint: joint_6
    pid: {p: 100.0, i: 1.0, d: 10.0}
  
  gripper:
    type: effort_controllers/JointPositionController
    joint: finger_R_joint
    pid: {p: 50.0, i: 0.1, d: 10.0}

  gripper_sub:
    type: effort_controllers/JointPositionController
    joint: finger_L_joint
    pid: {p: 50.0, i: 0.1, d: 10.0}

  wheel_1:
    type: velocity_controllers/JointVelocityController
    joint: right_front_mecanum_joint
    # pid: {p: 100.0, i: 1.0, d: 10.0}
    
  wheel_2:
    type: velocity_controllers/JointVelocityController
    joint: left_front_mecanum_joint
    # pid: {p: 100.0, i: 1.0, d: 10.0}

  wheel_3:
    type: velocity_controllers/JointVelocityController
    joint: left_back_mecanum_joint
    # pid: {p: 100.0, i: 1.0, d: 10.0}

  wheel_4:
    type: velocity_controllers/JointVelocityController
    joint: right_back_mecanum_joint
    # pid: {p: 100.0, i: 1.0, d: 10.0}