mecanum:
  #Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000

  gazebo_ros_control:
   pid_gains:

      front_L_wheel_joint: 
        p: 30.0
        i: 1.0 
        d: 10.0
      front_R_wheel_joint: 
        p: 30.0
        i: 1.0 
        d: 10.0
      back_L_wheel_joint: 
        p: 30.0
        i: 1.0 
        d: 10.0
      back_R_wheel_joint: 
        p: 30.0
        i: 1.0 
        d: 10.0
